/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_chaobao_androidmathematicalart_MathematicalArt */

#ifndef _Included_cn_chaobao_androidmathematicalart_MathematicalArt
#define _Included_cn_chaobao_androidmathematicalart_MathematicalArt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_chaobao_androidmathematicalart_MathematicalArt
 * Method:    jniGetMathematicalArt
 * Signature: (I)I
 */
JNIEXPORT jobject JNICALL Java_cn_chaobao_androidmathematicalart_MathematicalArt_jniGetMathematicalArt
  (JNIEnv *, jclass,jstring,jint);


#ifdef __cplusplus
}
#endif
#endif
